### ISSUE TITLE
Clarification of Test 2 needed in the Test Assurance Activities for SFR FDP_DSK_EXT.1 in HCD SD v1.0

### ISSUE THREAD

**Issue by ansukert** [HCD-iTC/HCD-IT#20]
An issue from Masatoshi Kawashima, Information Technology Security Center

HCD SD Version 1.0
**Section of HCD cPP/HCD SD in question (reference to SFR or subchapter in the HCD cPP or HCD SD):**
Section 3.1.3. FDP_DSK_EXT.1 Protection of Data on Disk” of HCD SD, Section 3.1.3.4. Tests”

**Issue:**
Test 2 of FDP_DSK_EXT.1 described in “3.1.3.4” of HCD SD requires the evaluator to verify that the data can be decrypted by proper key and key material. When the data is a key and encrypted by “another key that is not part of key chain” specified in FPT_KYP_EXT.1, the evaluator cannot decrypt the data, because “another key” cannot be retrieved from “protected storage device”.

**Proposed Resolution(if any):**
Test 2 needs annotation which states that decryption of the data is not required if the data is encrypted by “another key”.

**Rationale:**

**Comment by Ryuichiro-Ohya-FX** [comment]
In the current version of HCD cPP, there are two or three SFRs which require the keys in non-volatile storage to be protected. One of them is FDP_DSK_EXT.1, and another one is FPT_KYP_EXT.1. And I think FCS_KYC_EXT.1 is a supplemental requirement of FPT_KYP_EXT.1, which requires TOE to keep an effective strength of protection for the intermediate keys in the key chain.

At the current version of cPP and SD, we haven’t defined the Tests evaluation activities (EAs) of FPT_KYP_EXT.1 and FCS_KYC_EXT.1 while FDP_DSK_EXT.1 has Tests EA. KYP and KYC include only TSS and KMD EAs.

That’s why, it seems reasonable that Tests EAs are required for the protected keys by FDP_DSK_EXT.1.

But KMD EA of FCS_KYC_EXT.1 contains the following description.
“But the evaluator does not need to verify the protection method in detail for the start (or root) of key chain if the key to protect is not in the key chain specified in FCS_KYC_EXT.1. Also the evaluator does not need to verify the protection method implemented in the protected storage device if the key is stored in the protected storage device.”

So, I don’t think the proposed modification is necessary. Because the above description allows the evaluator to exempt to verify the encryption function for the start of key chain which is protected by another key.
Or, if it would be difficult to find the above annotation in FCS_KYC_EXT.1, then we should add a note like follows into Tests EA of FDP_DSK_EXT.1.

“This Test activity is not required for the start of key chain under either of the following conditions.
1. the start of key chain is protected by another key which is not in the key chain specified in FCS_KYC_EXT.1.
2. the start of key chain is stored in the protected storage device and protected by the protection method implementation of the storage device.”

**Comment by Ryuichiro-Ohya-FX** [comment]
Today I got a message from Kawashima-san of ITSC saying they withdraw this issue.
They found that protection of keys should be verified only with FPT_KYP_EXT.1 and FCS_KYC_EXT.1 and doesn’t need to be verified according to FDP_DSK_EXT.1.
If you don’t have any concern, shall we stop discussing about this issue?

**Comment by ansukert** [comment]
The following note was received from Ryuichiro Ohya-san on 11/29/2023:

Hello Alan-san, Jerry-san,

As for the issue #20, I got a message from Kawashima-san of ITSC saying they withdraw this issue. 

They found that protection of keys should be verified only with FPT_KYP_EXT.1 and FCS_KYC_EXT.1 and doesn’t need to be verified according to FDP_DSK_EXT.1. 

If you don’t have any concern, shall we stop discussing about this issue?

Best regards,
--------------------------- 
Ryuichiro Ohya 
Quality Assurance Department, 
FUJIFILM Business Innovation Corp.

**Comment by gcolunga** [comment]
Hello Ohya-san,

I agree with the withdrawal of issue #20<https://github.com/HCD-iTC/HCD-IT/issues/20> based on the recent information you have added to the issue.

Best regards,
Jerry

________________________________

**Comment by ansukert** [comment]
This issue was withdrawn by the author per the email below:

Hello Alan-san, Jerry-san,

As for the issue #20, I got a message from Kawashima-san of ITSC saying they withdraw this issue. 

They found that protection of keys should be verified only with FPT_KYP_EXT.1 and FCS_KYC_EXT.1 and doesn’t need to be verified according to FDP_DSK_EXT.1. 

If you don’t have any concern, shall we stop discussing about this issue?

Best regards,
--------------------------- 
Ryuichiro Ohya 

Quality Assurance Department, 

FUJIFILM Business Innovation Corp.

**Comment by ansukert** [comment]
Completed - Issue Withdrawn
