### ISSUE TITLE
Clarification of when Tests 3 and 4 are needed is required in the Text Assurance Activities for SFR FDP_DSK_EXT.1 in HCD SD v1.0 

### ISSUE THREAD

**Issue by ansukert** [HCD-iTC/HCD-IT#21]
A comment from Masatoshi Kawashima, Information Technology Security Center
HCD SD Version 1.0
Section “3.1.3. FDP_DSK_EXT.1 Protection of Data on Disk” of HCD SD, “3.1.3.4. Tests”

**Issue:**
As tests of FDP_DSK_EXT.1, Test 3 and Test 4 are required when data other than D.USER.DOC and D.TSF.CONF are encrypted. Test 3 and Test 4 are tests of data other than D.USER.DOC and D.TSF.CONF. I guess that these tests are required when Security Target claims FPT_WIPE_EXT.1, and the objects of the FPT_WIPE_EXT.1 are made unavailable using cryptographic erase. Unless FPT_WIPE_EXT.1 is claimed, Test 3 and Test 4 are not required, because the objects of FDP_DSK_EXT.1 are D.USER.DOC and D.TSF.CONF. But from the description of Section 3.1.3.4. of SD, Test 3 and Test 4 seem to be mandatory regardless whether FPT_WIPE_EXT.1 is claimed or not.

**Proposed Resolution(if any):**

The condition in which Test 3 and Test 4 are required should be clearly described.

**Comment by Ryuichiro-Ohya-FX** [comment]
This issue might not be high priority, because I’m not sure if any vendor would claim FPT_WIPE_EXT.1 using cryptographic erase technique.

But for a case someone needs to claim FPT_WIPE_EXT.1, I’m going to make a comment for this issue.

I propose to leave the descriptions for Test 3 and Test 4 as they are. Otherwise, the conditions should be modified as follows.
“Test 3. (_**If ST author claims FPT_WIPE_EXT.1 with cryptographic erase, and**_ if data other than D.USER.DOC and D.TSF.CONF are encrypted,) write the data to the storage device with operating TSFI which enforce write process of the data.
Test 4. (_**If ST author claims FPT_WIPE_EXT.1 with cryptographic erase, and**_ if data other than D.USER.DOC and D.TSF.CONF are encrypted,) verify that the data written in Test 3 is not in plaintext form; and verify that the data can be decrypted by proper key and key
material.“

The rationale is as following.

As you know, the original intention of FDP_DSK_EXT.1 is to encrypt D.USER.DOC and D.TSF.CONF. However, when the cryptographic erase method was added as one of methods for FPT_WIPE_EXT.1, some modifications were made.

- Application Note for FDP_DSK_EXT.1.2
The following description was added.
“If additional data other than D.USER.DOC and D.TSF.CONF are encrypted, it will be wiped/purged by the cryptographic erase process.”

- TSS evaluation activity for FDP_DSK_EXT.1 (3.1.3.1)
The following description was added.
“If data (e.g., D.USER.JOB, D.TSF.PROT) other than D.USER.DOC and D.TSF.CONF are encrypted, the evaluator shall verify that TSS identifies all such data and states that no other customer-supplied data are encrypted.”

- Tests evaluation activity for FDP_DSK_EXT.1 (3.1.3.4)
The following description was added.
“Test 3. (If data other than D.USER.DOC and D.TSF.CONF are encrypted,) write the data to the storage device with operating TSFI which enforce write process of the data.
Test 4. (If data other than D.USER.DOC and D.TSF.CONF are encrypted,) verify that the data written in Test 3 is not in plaintext form; and verify that the data can be decrypted by proper key and key
material.”

The testing lab is saying that the problem is Test 3 and Test 4 are required even if ST author doesn’t claim FPT_WIPE_EXT.1.
However, ST author, who doesn’t claim FDP_WIPE_EXT.1, won’t include such data in TSS of FDP_DSK_EXT.1. That’s why, I don’t think Test 3 and Test 4 are required for such a product.

**Comment by gcolunga** [comment]
This issue is addressed by the following TD: 

- HCD0008

The TD above is located at the following location: 

- https://github.com/HCD-iTC/HCD-iTC-Template/tree/Working/TD
